--------------------------------------------------------
--  파일이 생성됨 - 수요일-3월-24-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NAMECARD
--------------------------------------------------------

  CREATE TABLE "C##EXAM"."NAMECARD" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(10 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##EXAM.NAMECARD
SET DEFINE OFF;
Insert into C##EXAM.NAMECARD (ID,NAME,TEL,EMAIL,ADDRESS) values (1,'홍길동','010-1111-1111','hong@gmail.com','서울시 집주소');
Insert into C##EXAM.NAMECARD (ID,NAME,TEL,EMAIL,ADDRESS) values (3,'박길동','010-3333-3333','park@daum.net','대구시 집주소');
Insert into C##EXAM.NAMECARD (ID,NAME,TEL,EMAIL,ADDRESS) values (21,'김길동','010-2222-2222','kim@naver.com','대전시 집주소');
--------------------------------------------------------
--  DDL for Index PK_NAMECARD_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EXAM"."PK_NAMECARD_ID" ON "C##EXAM"."NAMECARD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table NAMECARD
--------------------------------------------------------

  ALTER TABLE "C##EXAM"."NAMECARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##EXAM"."NAMECARD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##EXAM"."NAMECARD" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "C##EXAM"."NAMECARD" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "C##EXAM"."NAMECARD" ADD CONSTRAINT "PK_NAMECARD_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
