--------------------------------------------------------
--  파일이 생성됨 - 수요일-3월-10-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STUDENTADDR
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."STUDENTADDR" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"ADDR" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##SCOTT.STUDENTADDR
SET DEFINE OFF;
Insert into C##SCOTT.STUDENTADDR (ID,NAME,AGE,ADDR) values (0,'bbb',55,'3월 10일 실습중');
Insert into C##SCOTT.STUDENTADDR (ID,NAME,AGE,ADDR) values (1,'수정했다.',999,'수정수정수정수정수정');
Insert into C##SCOTT.STUDENTADDR (ID,NAME,AGE,ADDR) values (33,'????',555,'5555555');
Insert into C##SCOTT.STUDENTADDR (ID,NAME,AGE,ADDR) values (34,'????',555,'5555555');
Insert into C##SCOTT.STUDENTADDR (ID,NAME,AGE,ADDR) values (61,'와르르 맨션',100,'99_3월 10일 실습중');
--------------------------------------------------------
--  DDL for Index PK_STUDENT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."PK_STUDENT_ID" ON "C##SCOTT"."STUDENTADDR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table STUDENTADDR
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."STUDENTADDR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."STUDENTADDR" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."STUDENTADDR" MODIFY ("ADDR" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."STUDENTADDR" ADD CONSTRAINT "PK_STUDENT_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
