--------------------------------------------------------
--  파일이 생성됨 - 월요일-3월-15-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_CUSTOMER
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."T_CUSTOMER" 
   (	"I_CUSTOMER" NUMBER(*,0), 
	"CUSTOMER_NM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_GRADE
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."T_GRADE" 
   (	"SID" NUMBER(*,0), 
	"LECTURE_NM" VARCHAR2(20 BYTE), 
	"STUDENT_GRADE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_LECTURE
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."T_LECTURE" 
   (	"LECTURE_NM" VARCHAR2(30 BYTE), 
	"CLASS_LOCATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_NETFLIX
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."T_NETFLIX" 
   (	"I_CUSTOMER" NUMBER(*,0), 
	"CUS_WATCHING" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_STUDENT
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."T_STUDENT" 
   (	"SID" NUMBER(*,0), 
	"STUDENT_NM" VARCHAR2(10 BYTE), 
	"STUDENT_ADDR" VARCHAR2(50 BYTE), 
	"LECTURE_NM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##SCOTT.T_CUSTOMER
SET DEFINE OFF;
Insert into C##SCOTT.T_CUSTOMER (I_CUSTOMER,CUSTOMER_NM) values (100,'홍길동');
REM INSERTING into C##SCOTT.T_GRADE
SET DEFINE OFF;
Insert into C##SCOTT.T_GRADE (SID,LECTURE_NM,STUDENT_GRADE) values (400,'궁술과',3);
REM INSERTING into C##SCOTT.T_LECTURE
SET DEFINE OFF;
Insert into C##SCOTT.T_LECTURE (LECTURE_NM,CLASS_LOCATION) values ('검술과','공학관 501호');
Insert into C##SCOTT.T_LECTURE (LECTURE_NM,CLASS_LOCATION) values ('궁술과','공학관 502호');
Insert into C##SCOTT.T_LECTURE (LECTURE_NM,CLASS_LOCATION) values ('창술과','공학관 503호');
REM INSERTING into C##SCOTT.T_NETFLIX
SET DEFINE OFF;
REM INSERTING into C##SCOTT.T_STUDENT
SET DEFINE OFF;
Insert into C##SCOTT.T_STUDENT (SID,STUDENT_NM,STUDENT_ADDR,LECTURE_NM) values (100,'홍길동','조선 한양 홍대감댁','검술과');
Insert into C##SCOTT.T_STUDENT (SID,STUDENT_NM,STUDENT_ADDR,LECTURE_NM) values (101,'김길동','조선 한양 김대감댁','궁술과');
Insert into C##SCOTT.T_STUDENT (SID,STUDENT_NM,STUDENT_ADDR,LECTURE_NM) values (102,'박길동','조선 한양 박대감댁','창술과');
--------------------------------------------------------
--  DDL for Index SYS_C007621
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."SYS_C007621" ON "C##SCOTT"."T_CUSTOMER" ("I_CUSTOMER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007696
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."SYS_C007696" ON "C##SCOTT"."T_GRADE" ("SID", "LECTURE_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007692
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."SYS_C007692" ON "C##SCOTT"."T_LECTURE" ("LECTURE_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007623
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."SYS_C007623" ON "C##SCOTT"."T_NETFLIX" ("I_CUSTOMER", "CUS_WATCHING") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007689
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."SYS_C007689" ON "C##SCOTT"."T_STUDENT" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table T_CUSTOMER
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."T_CUSTOMER" MODIFY ("CUSTOMER_NM" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."T_CUSTOMER" ADD PRIMARY KEY ("I_CUSTOMER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_GRADE
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."T_GRADE" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."T_GRADE" MODIFY ("LECTURE_NM" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."T_GRADE" MODIFY ("STUDENT_GRADE" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."T_GRADE" ADD PRIMARY KEY ("SID", "LECTURE_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_LECTURE
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."T_LECTURE" MODIFY ("LECTURE_NM" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."T_LECTURE" MODIFY ("CLASS_LOCATION" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."T_LECTURE" ADD PRIMARY KEY ("LECTURE_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_NETFLIX
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."T_NETFLIX" MODIFY ("CUS_WATCHING" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."T_NETFLIX" ADD PRIMARY KEY ("I_CUSTOMER", "CUS_WATCHING")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_STUDENT
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."T_STUDENT" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."T_STUDENT" MODIFY ("STUDENT_NM" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."T_STUDENT" MODIFY ("STUDENT_ADDR" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."T_STUDENT" MODIFY ("LECTURE_NM" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."T_STUDENT" ADD PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_NETFLIX
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."T_NETFLIX" ADD FOREIGN KEY ("I_CUSTOMER")
	  REFERENCES "C##SCOTT"."T_CUSTOMER" ("I_CUSTOMER") ENABLE;
